version: "3.9"

services:
  weather-service:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      weather-db:
        condition: service_healthy
    environment:
      HOST: weather-db
      PORT: 5432
      DB_NAME: weather_service_db
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: qwerty
      API_KEY: 9bac7c57f5cb478752b6bdb67729f38d
      WEATHER_API_URL: https://api.openweathermap.org/data/2.5/weather
      SERVICE_URL: http://weather-service:8080/weather

  weather-db:
    image: postgres:17.2
    container_name: weather_db
    ports:
      - "5436:5432"
    volumes:
      - data-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weather_service_db
      POSTGRES_USER: ilya
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/psqldata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ilya -d weather_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  data-storage:
